services:
  postgres:
    image: postgres:16
    container_name: poker-planning
    environment:
      POSTGRES_DB: poker-planning-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 523349
    ports:
      - "5436:5432"
    volumes:
      - poker-planning_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d poker-planning"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  poker-planning_pgdata: